const express = require("express");
const { getMeetingTypes, getMyBookings } = require("../controllers/meetingController");
const { cancelBooking } = require("../controllers/bookingController");
const { requestPayment } = require("../controllers/manualPaymentController");
const authenticate = require("../middleware/authenticate");
const router = express.Router();
router.get("/types", getMeetingTypes);
router.get("/bookings", authenticate, getMyBookings);
router.post("/bookings/initialize", authenticate, (req, res) => { req.body.type = "MEETING"; req.body.itemId = req.body.meetingTypeId; return requestPayment(req, res); });
router.patch("/bookings/:id/cancel", authenticate, cancelBooking);
module.exports = router;
