const express = require("express");
const { getMembershipPlans, getMyMembership, getPaymentHistory, getMembershipCard } = require("../controllers/membershipController");
const { requestPayment } = require("../controllers/manualPaymentController");
const authenticate = require("../middleware/authenticate");
const router = express.Router();
router.get("/plans", getMembershipPlans);
router.post("/initialize", authenticate, (req, res) => { req.body.type = "MEMBERSHIP"; req.body.itemId = req.body.planId; return requestPayment(req, res); });
router.get("/payments", authenticate, getPaymentHistory);
router.get("/card", authenticate, getMembershipCard);
router.get("/me", authenticate, getMyMembership);
module.exports = router;
