const express = require("express");
const { getUnreadCount, getMyNotifications, markAsRead, markAllAsRead, deleteNotification } = require("../controllers/notificationController");
const authenticate = require("../middleware/authenticate");
const router = express.Router();
router.get("/unread-count", authenticate, getUnreadCount);
router.get("/", authenticate, getMyNotifications);
router.patch("/read-all", authenticate, markAllAsRead);
router.patch("/:id/read", authenticate, markAsRead);
router.delete("/:id", authenticate, deleteNotification);
module.exports = router;
