const express = require("express");
const cors = require("cors");
const helmet = require("helmet");
const morgan = require("morgan");
const authRoutes = require("./routes/authRoutes");
const otpRoutes = require("./routes/otpRoutes");
const membershipRoutes = require("./routes/membershipRoutes");
const paymentRoutes = require("./routes/paymentRoutes");
const paymentConfigRoutes = require("./routes/paymentConfigRoutes");
const postRoutes = require("./routes/postRoutes");
const commentRoutes = require("./routes/commentRoutes");
const likeRoutes = require("./routes/likeRoutes");
const meetingRoutes = require("./routes/meetingRoutes");
const giftRoutes = require("./routes/giftRoutes");
const notificationRoutes = require("./routes/notificationRoutes");
const adminRoutes = require("./routes/adminRoutes");
const eventRoutes = require("./routes/eventRoutes");
const analyticsRoutes = require("./routes/analyticsRoutes");
const paystackWebhookRoutes = require("./routes/paystackWebhookRoutes");
const flutterwaveWebhookRoutes = require("./routes/flutterwaveWebhookRoutes");
const errorHandler = require("./middleware/errorHandler");
const app = express();
app.use(helmet());app.use(cors({origin:process.env.CLIENT_URL||"http://localhost:5173",credentials:true}));
app.use("/api/payments/mine",express.json({limit:"7mb"}),express.urlencoded({extended:true,limit:"7mb"}));
app.use("/api/payment-config",express.json({limit:"7mb"}),express.urlencoded({extended:true,limit:"7mb"}));
app.use(express.json({limit:"200kb"}));app.use(express.urlencoded({extended:true,limit:"200kb"}));if(process.env.NODE_ENV!=="production")app.use(morgan("dev"));
app.use("/api/auth",authRoutes);app.use("/api/otp",otpRoutes);app.use("/api/memberships",membershipRoutes);app.use("/api/payments",paymentRoutes);app.use("/api/payment-config",paymentConfigRoutes);app.use("/api/posts",postRoutes);app.use("/api",commentRoutes);app.use("/api",likeRoutes);app.use("/api/meetings",meetingRoutes);app.use("/api/gifts",giftRoutes);app.use("/api/notifications",notificationRoutes);app.use("/api/admin",adminRoutes);app.use("/api/events",eventRoutes);app.use("/api/analytics",analyticsRoutes);app.use("/api/paystack",paystackWebhookRoutes);app.use("/api/flutterwave",flutterwaveWebhookRoutes);
app.get("/api/health",(req,res)=>res.status(200).json({success:true,message:"Keanu Reeves Fan Community API is running.",timestamp:new Date().toISOString()}));app.use(errorHandler);module.exports=app;
