import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import '../styles/admin.css'
const API_BASE_URL=import.meta.env.VITE_API_URL||'http://localhost:5000/api'
const money=(a,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(a||0)/100)
export default function AdminPaymentsPage(){
 const {token,user}=useAuth(); const [payments,setPayments]=useState([]); const [support,setSupport]=useState(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(null)
 const load=async()=>{setLoading(true);try{const r=await fetch(`${API_BASE_URL}/admin/payments/pending`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Unable to load payment requests.');setPayments(d.payments||[]);const s=await fetch(`${API_BASE_URL}/payments/support`);const sd=await s.json();if(sd.success)setSupport(sd.support)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{if(token&&user?.role==='ADMIN')load()},[token,user?.role])
 const confirm=async id=>{setBusy(id);try{const r=await fetch(`${API_BASE_URL}/admin/payments/${id}/confirm`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Unable to confirm payment.');await load()}catch(e){setError(e.message)}finally{setBusy(null)}}
 if(user?.role!=='ADMIN')return <main className="placeholder-page"><h1>Access denied</h1><Link to="/">Return home</Link></main>
 return <main className="admin-page page-container"><header className="page-header"><p className="eyebrow">PAYMENT OPERATIONS</p><h1>Manual payment requests</h1><p className="muted">Members provide the payment token to the designated support administrator. Confirm a request only after payment has been received.</p><div className="admin-links"><Link className="secondary-button" to="/admin">Dashboard</Link><Link className="secondary-button" to="/admin/manage">Management</Link></div></header>{support&&<section className="admin-revenue"><span className="eyebrow">DESIGNATED PAYMENT SUPPORT</span><h2>{support.name}</h2><p>{support.email} · @{support.username}</p><p className="muted">Only the designated support administrator can confirm a payment.</p></section>}{error&&<p className="auth-error">{error}</p>}{loading?<p>Loading payment requests…</p>:payments.length===0?<section className="dashboard-panel"><h2>No pending payment requests</h2><p className="muted">New membership, meeting and gift requests will appear here.</p></section>:<section className="admin-table-wrap"><table><thead><tr><th>Member</th><th>Purchase</th><th>Amount</th><th>Token</th><th>Created</th><th>Action</th></tr></thead><tbody>{payments.map(p=><tr key={p._id}><td>{p.user?.name||p.user?.username}<small>{p.user?.email}</small></td><td>{p.metadata?.description||p.type}</td><td>{money(p.originalAmount,p.originalCurrency)}</td><td><code>{p.paymentToken}</code></td><td>{new Date(p.createdAt).toLocaleString()}</td><td><button disabled={busy===p._id||user?._id!==support?._id} onClick={()=>confirm(p._id)}>{busy===p._id?'Confirming…':'Mark successful'}</button></td></tr>)}</tbody></table></section>}</main>
}
