import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import '../styles/gifts.css'
const API_BASE_URL=import.meta.env.VITE_API_URL||'http://localhost:5000/api'
const formatMoney=(amount,currency='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency}).format(Number(amount||0)/100)
const statusLabel=status=>String(status||'').replaceAll('_',' ')
export default function GiftsPage(){const{token,user}=useAuth();const navigate=useNavigate();const[gifts,setGifts]=useState([]),[history,setHistory]=useState([]),[summary,setSummary]=useState(null),[filter,setFilter]=useState('ALL'),[selectedGift,setSelectedGift]=useState(null),[quantity,setQuantity]=useState(1),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[historyLoading,setHistoryLoading]=useState(false),[submitting,setSubmitting]=useState(false),[error,setError]=useState('')
const loadHistory=async(selectedFilter=filter)=>{if(!token)return;setHistoryLoading(true);try{const q=selectedFilter!=='ALL'?`?status=${selectedFilter}`:'';const r=await fetch(`${API_BASE_URL}/gifts/history${q}`,{headers:{Authorization:`Bearer ${token}`}}),d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Unable to load gift history.');setHistory(d.data?.transactions||[]);setSummary(d.data?.summary||null)}catch(e){setError(e.message)}finally{setHistoryLoading(false)}}
useEffect(()=>{let cancelled=false;(async()=>{try{const requests=[fetch(`${API_BASE_URL}/gifts`)];if(token)requests.push(fetch(`${API_BASE_URL}/gifts/history`,{headers:{Authorization:`Bearer ${token}`}}));const[g,h]=await Promise.all(requests),gd=await g.json();if(!cancelled&&g.ok&&gd.success)setGifts(gd.data?.gifts||[]);if(h){const hd=await h.json();if(!cancelled&&h.ok&&hd.success){setHistory(hd.data?.transactions||[]);setSummary(hd.data?.summary||null)}}}catch{if(!cancelled)setError('Unable to load gifts. Please try again.')}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[token])
const filteredHistory=useMemo(()=>history,[history]);const openGiftModal=gift=>{if(!user){navigate('/login');return}setSelectedGift(gift);setQuantity(1);setMessage('');setError('')};const closeGiftModal=()=>{if(!submitting)setSelectedGift(null)}
const handlePurchase=async event=>{event.preventDefault();if(!selectedGift||!token)return;setSubmitting(true);setError('');try{const r=await fetch(`${API_BASE_URL}/gifts/initialize`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({giftId:selectedGift._id,quantity,message})}),d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Unable to create payment request.');setSelectedGift(null);navigate(`/payment/pending/${encodeURIComponent(d.payment.token)}`)}catch(e){setError(e.message)}finally{setSubmitting(false)}}
if(loading)return <main className="gifts-page"><header className="gifts-hero"><div><p className="eyebrow">FAN APPRECIATION</p><h1>Give a little.</h1></div><p>Loading the gift collection…</p></header></main>
return <main className="gifts-page"><header className="gifts-hero"><div><p className="eyebrow">FAN APPRECIATION</p><h1>Give a little.</h1></div><div className="gifts-hero-copy"><p>Send a virtual gift as a simple expression of appreciation. Choose something meaningful, add a personal note, and complete payment through our designated support administrator.</p><Link className="text-link" to="/community">Explore the community <span>→</span></Link></div></header>{!user&&<div className="gift-login"><Link to="/login">Sign in</Link> to send a gift. You can explore the collection without an account.</div>}{error&&!selectedGift&&<div className="gift-login gift-error">{error}</div>}
<section className="gift-collection" aria-label="Gift collection">{gifts.map((gift,index)=><article className={`gift-showcase gift-showcase-${index%5}`} key={gift._id}><div className="gift-orbit" aria-hidden="true"><span>{gift.image?<img src={gift.image} alt=""/>:'✦'}</span></div><div className="gift-content"><span className="gift-index">GIFT {String(index+1).padStart(2,'0')}</span><h2>{gift.name}</h2><p className="gift-price">{formatMoney(gift.price,gift.currency)}</p><p>{gift.description}</p>{user?<button className="button button-primary" type="button" onClick={()=>openGiftModal(gift)}>Send this gift →</button>:<Link className="button button-ghost" to="/login">Sign in to send</Link>}</div></article>)}</section>{gifts.length===0&&!error&&<p className="gift-empty">No gifts are available right now.</p>}
{user&&<section className="gift-history" aria-labelledby="gift-history-title"><div className="gift-history-heading"><div><p className="eyebrow">YOUR APPRECIATION</p><h2 id="gift-history-title">Gift dashboard</h2></div><button className="button button-ghost" type="button" onClick={()=>loadHistory()} disabled={historyLoading}>{historyLoading?'Refreshing…':'Refresh'}</button></div>{summary&&<div className="gift-stats"><div><span>Completed</span><strong>{summary.completed}</strong></div><div><span>Gift units</span><strong>{summary.totalGiftUnits}</strong></div><div><span>Pending</span><strong>{summary.pending}</strong></div><div><span>Completed value</span><strong>{formatMoney(summary.completedAmount,'USD')}</strong></div></div>}<div className="gift-history-toolbar" role="group" aria-label="Filter gift history">{['ALL','COMPLETED','PENDING_PAYMENT','FAILED','CANCELLED'].map(value=><button key={value} className={filter===value?'active':''} type="button" onClick={()=>{setFilter(value);loadHistory(value)}}>{value==='ALL'?'All':statusLabel(value)}</button>)}</div>{historyLoading&&!filteredHistory.length?<p className="gift-empty">Loading your gift history…</p>:filteredHistory.length?<div className="gift-history-list">{filteredHistory.map(t=><article className="gift-history-card" key={t._id}><div className="gift-history-icon">{t.gift?.image?<img src={t.gift.image} alt=""/>:'✦'}</div><div className="gift-history-main"><div className="gift-history-title"><strong>{t.gift?.name||'Gift'}</strong><span className={`gift-status gift-status-${String(t.status).toLowerCase()}`}>{statusLabel(t.status)}</span></div><p>{t.quantity} {t.quantity===1?'unit':'units'} · {formatMoney(t.amount,t.gift?.currency||'USD')} · {new Date(t.createdAt).toLocaleDateString()}</p><code>{t.reference}</code>{t.message&&<blockquote>“{t.message}”</blockquote>}</div></article>)}</div>:<div className="gift-history-empty"><strong>No gifts in this view.</strong><span>Completed purchases and payment attempts will appear here.</span></div>}</section>}
<section className="gifts-note section-shell"><div><p className="eyebrow">A SMALL GESTURE</p><h2>Make the moment personal.</h2></div><p>Every gift can carry your own message. Whether it is a celebration, a thank-you, or simply a sign of support, the note makes the experience yours.</p></section>
{selectedGift&&<form className="gift-modal-backdrop" onSubmit={handlePurchase}><div className="gift-modal" role="dialog" aria-modal="true"><p className="eyebrow">SEND A GIFT</p><h2>{selectedGift.name}</h2><p className="gift-modal-price">{formatMoney(selectedGift.price,selectedGift.currency)} each</p><label>Quantity<input type="number" min="1" max="100" required value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(100,Number(e.target.value)||1)))}/></label><label>Message (optional)<textarea rows="4" maxLength="500" placeholder="Add a message of appreciation…" value={message} onChange={e=>setMessage(e.target.value)}/></label><p className="gift-total">Total <strong>{formatMoney(selectedGift.price*quantity,selectedGift.currency)}</strong></p><p className="muted">After you continue, you will receive a payment token and the designated support administrator's contact details.</p>{error&&<p className="gift-error">{error}</p>}<div className="gift-modal-actions"><button className="button button-primary" type="submit" disabled={submitting}>{submitting?'Creating payment request…':'Create payment request'}</button><button className="button button-ghost" type="button" disabled={submitting} onClick={closeGiftModal}>Cancel</button></div></div></form>}</main>}
