import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import '../styles/gifts.css'

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api'
const formatMoney = (amount, currency = 'USD') => new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(Number(amount || 0) / 100)
const statusLabel = (status) => String(status || '').replaceAll('_', ' ')

export default function GiftsPage() {
  const { token, user } = useAuth()
  const [gifts, setGifts] = useState([]); const [history, setHistory] = useState([]); const [summary, setSummary] = useState(null)
  const [filter, setFilter] = useState('ALL'); const [selectedGift, setSelectedGift] = useState(null); const [quantity, setQuantity] = useState(1); const [message, setMessage] = useState('')
  const [loading, setLoading] = useState(true); const [historyLoading, setHistoryLoading] = useState(false); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const [needsOtp, setNeedsOtp] = useState(false); const [otp, setOtp] = useState(''); const [otpSending, setOtpSending] = useState(false)

  const loadHistory = async (selectedFilter = filter) => { if (!token) return; setHistoryLoading(true); try { const query = selectedFilter !== 'ALL' ? `?status=${selectedFilter}` : ''; const response = await fetch(`${API_BASE_URL}/gifts/history${query}`, { headers: { Authorization: `Bearer ${token}` } }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.message || 'Unable to load gift history.'); setHistory(data.data?.transactions || []); setSummary(data.data?.summary || null) } catch (e) { setError(e.message) } finally { setHistoryLoading(false) } }

  useEffect(() => { let cancelled = false; const loadData = async () => { try { const requests = [fetch(`${API_BASE_URL}/gifts`)]; if (token) requests.push(fetch(`${API_BASE_URL}/gifts/history`, { headers: { Authorization: `Bearer ${token}` } })); const [giftsResponse, historyResponse] = await Promise.all(requests); const giftsData = await giftsResponse.json(); if (!cancelled && giftsResponse.ok && giftsData.success) setGifts(giftsData.data?.gifts || []); if (historyResponse) { const historyData = await historyResponse.json(); if (!cancelled && historyResponse.ok && historyData.success) { setHistory(historyData.data?.transactions || []); setSummary(historyData.data?.summary || null) } } } catch { if (!cancelled) setError('Unable to load gifts. Please try again.') } finally { if (!cancelled) setLoading(false) } }; loadData(); return () => { cancelled = true } }, [token])

  const filteredHistory = useMemo(() => history, [history])
  const openGiftModal = (gift) => { setSelectedGift(gift); setQuantity(1); setMessage(''); setError(''); setNeedsOtp(false); setOtp('') }; const closeGiftModal = () => { if (!submitting) setSelectedGift(null) }
  const requestPurchaseOtp = async () => { setOtpSending(true); setError(''); try { const r = await fetch(`${API_BASE_URL}/otp/purchase/request`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }); const d = await r.json(); if (!r.ok || !d.success) throw new Error(d.message || 'Unable to send verification code.'); setNeedsOtp(true) } catch (e) { setError(e.message) } finally { setOtpSending(false) } }
  const handlePurchase = async (event) => { event.preventDefault(); if (!selectedGift || !token) return; setSubmitting(true); setError(''); try { const response = await fetch(`${API_BASE_URL}/gifts/initialize`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ giftId: selectedGift._id, quantity, message, ...(otp ? { otp } : {}) }) }); const data = await response.json(); if (response.status === 428 && data.requiresOtp) { await requestPurchaseOtp(); return } if (!response.ok || !data.success) throw new Error(data.message || 'Unable to start gift checkout.'); window.location.href = data.checkout.authorizationUrl } catch (purchaseError) { setError(purchaseError.message) } finally { setSubmitting(false) } }

  if (loading) return <main className="gifts-page"><header className="gifts-hero"><div><p className="eyebrow">FAN APPRECIATION</p><h1>Give a little.</h1></div><p>Loading the gift collection…</p></header></main>
  return <main className="gifts-page"><header className="gifts-hero"><div><p className="eyebrow">FAN APPRECIATION</p><h1>Give a little.</h1></div><div className="gifts-hero-copy"><p>Send a virtual gift as a simple expression of appreciation. Choose something meaningful, add a personal note, and complete your gift securely through Paystack.</p><Link className="text-link" to="/community">Explore the community <span>→</span></Link></div></header>{!user && <div className="gift-login"><Link to="/login">Sign in</Link> to send a gift. You can explore the collection without an account.</div>}{error && !selectedGift && <div className="gift-login gift-error">{error}</div>}
    <section className="gift-collection" aria-label="Gift collection">{gifts.map((gift, index) => <article className={`gift-showcase gift-showcase-${index % 5}`} key={gift._id}><div className="gift-orbit" aria-hidden="true"><span>{gift.image ? <img src={gift.image} alt="" /> : '✦'}</span></div><div className="gift-content"><span className="gift-index">GIFT {String(index + 1).padStart(2, '0')}</span><h2>{gift.name}</h2><p className="gift-price">{formatMoney(gift.price, gift.currency)}</p><p>{gift.description}</p>{user ? <button className="button button-primary" type="button" onClick={() => openGiftModal(gift)}>Send this gift →</button> : <Link className="button button-ghost" to="/login">Sign in to send</Link>}</div></article>)}</section>{gifts.length === 0 && !error && <p className="gift-empty">No gifts are available right now.</p>}
    {user && <section className="gift-history" aria-labelledby="gift-history-title"><div className="gift-history-heading"><div><p className="eyebrow">YOUR APPRECIATION</p><h2 id="gift-history-title">Gift dashboard</h2></div><button className="button button-ghost" type="button" onClick={() => loadHistory()} disabled={historyLoading}>{historyLoading ? 'Refreshing…' : 'Refresh'}</button></div>
      {summary && <div className="gift-stats"><div><span>Completed</span><strong>{summary.completed}</strong></div><div><span>Gift units</span><strong>{summary.totalGiftUnits}</strong></div><div><span>Pending</span><strong>{summary.pending}</strong></div><div><span>Completed value</span><strong>{formatMoney(summary.completedAmount, 'USD')}</strong></div></div>}
      <div className="gift-history-toolbar" role="group" aria-label="Filter gift history">{['ALL','COMPLETED','PENDING_PAYMENT','FAILED','CANCELLED'].map((value) => <button key={value} className={filter === value ? 'active' : ''} type="button" onClick={() => { setFilter(value); loadHistory(value) }}>{value === 'ALL' ? 'All' : statusLabel(value)}</button>)}</div>
      {historyLoading && !filteredHistory.length ? <p className="gift-empty">Loading your gift history…</p> : filteredHistory.length ? <div className="gift-history-list">{filteredHistory.map((transaction) => <article className="gift-history-card" key={transaction._id}><div className="gift-history-icon">{transaction.gift?.image ? <img src={transaction.gift.image} alt="" /> : '✦'}</div><div className="gift-history-main"><div className="gift-history-title"><strong>{transaction.gift?.name || 'Gift'}</strong><span className={`gift-status gift-status-${String(transaction.status).toLowerCase()}`}>{statusLabel(transaction.status)}</span></div><p>{transaction.quantity} {transaction.quantity === 1 ? 'unit' : 'units'} · {formatMoney(transaction.amount, transaction.gift?.currency || 'USD')} · {new Date(transaction.createdAt).toLocaleDateString()}</p><code>{transaction.reference}</code>{transaction.message && <blockquote>“{transaction.message}”</blockquote>}</div></article>)}</div> : <div className="gift-history-empty"><strong>No gifts in this view.</strong><span>Completed purchases and payment attempts will appear here.</span></div>}
    </section>}
    <section className="gifts-note section-shell"><div><p className="eyebrow">A SMALL GESTURE</p><h2>Make the moment personal.</h2></div><p>Every gift can carry your own message. Whether it is a celebration, a thank-you, or simply a sign of support, the note makes the experience yours.</p></section>
    {selectedGift && <form className="gift-modal-backdrop" onSubmit={handlePurchase}><div className="gift-modal" role="dialog" aria-modal="true" aria-labelledby="gift-dialog-title"><p className="eyebrow">SEND A GIFT</p><h2 id="gift-dialog-title">{selectedGift.name}</h2><p className="gift-modal-price">{formatMoney(selectedGift.price, selectedGift.currency)} each</p><label>Quantity<input type="number" min="1" max="100" required value={quantity} onChange={(event) => setQuantity(Math.max(1, Math.min(100, Number(event.target.value) || 1)))} /></label><label>Message (optional)<textarea rows="4" maxLength="500" placeholder="Add a message of appreciation…" value={message} onChange={(event) => setMessage(event.target.value)} /></label><p className="gift-total">Total <strong>{formatMoney(selectedGift.price * quantity, selectedGift.currency)}</strong></p>{needsOtp && <label>Purchase verification code<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={otp} onChange={(e) => setOtp(e.target.value.replace(/\D/g, ''))} placeholder="000000" required /></label>}{error && <p className="gift-error">{error}</p>}<div className="gift-modal-actions"><button className="button button-primary" type="submit" disabled={submitting || (needsOtp && otp.length !== 6)}>{submitting ? 'Redirecting to Paystack…' : needsOtp ? 'Verify & Continue' : 'Continue to payment'}</button>{needsOtp && <button className="button button-ghost" type="button" disabled={otpSending} onClick={requestPurchaseOtp}>{otpSending ? 'Sending…' : 'Resend code'}</button>}<button className="button button-ghost" type="button" disabled={submitting} onClick={closeGiftModal}>Cancel</button></div></div></form>}</main>
}
