import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import '../styles/meetings.css'
const API_BASE_URL=import.meta.env.VITE_API_URL||'http://localhost:5000/api'
const minDate=()=>new Date(Date.now()+60*60*1000).toISOString().slice(0,16)
const money=(a,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(a||0)/100)
export default function MeetingsPage(){const{token,user}=useAuth();const navigate=useNavigate();const[types,setTypes]=useState([]),[bookings,setBookings]=useState([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[scheduled,setScheduled]=useState(''),[notes,setNotes]=useState(''),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false)
useEffect(()=>{let cancelled=false;(async()=>{try{const requests=[fetch(`${API_BASE_URL}/meetings/types`)];if(token)requests.push(fetch(`${API_BASE_URL}/meetings/bookings`,{headers:{Authorization:`Bearer ${token}`}}));const[t,b]=await Promise.all(requests),td=await t.json();if(t.ok&&td.success&&!cancelled)setTypes(td.data?.meetingTypes||[]);if(b){const bd=await b.json();if(b.ok&&bd.success&&!cancelled)setBookings(bd.data?.bookings||[])}}catch{if(!cancelled)setError('Unable to load meeting experiences.')}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[token])
const open=type=>{if(!user){navigate('/login');return}setSelected(type);setScheduled('');setNotes('');setError('')}
const book=async e=>{e.preventDefault();if(!selected)return;setSubmitting(true);setError('');try{const r=await fetch(`${API_BASE_URL}/meetings/bookings/initialize`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({meetingTypeId:selected._id,scheduledFor:new Date(scheduled).toISOString(),notes})}),d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Unable to create payment request.');setSelected(null);navigate(`/payment/pending/${encodeURIComponent(d.payment.token)}`)}catch(e){setError(e.message)}finally{setSubmitting(false)}}
if(loading)return <main className="dashboard-page"><section className="dashboard-hero page-container"><span className="eyebrow">PRIVATE EXPERIENCES</span><h1>Preparing your meeting dashboard.</h1><p>Loading available experiences…</p></section></main>
return <main className="dashboard-page"><header className="dashboard-hero page-container"><div><span className="eyebrow">MEETING HUB</span><h1>Private experiences, organized around you.</h1><p>Choose an available experience, schedule your preferred time and complete payment through our designated support administrator.</p></div><div className="dashboard-status-card"><span>YOUR BOOKINGS</span><strong>{bookings.length}</strong><small>recorded experience{bookings.length===1?'':'s'}</small></div></header>{error&&!selected&&<div className="membership-alert page-container">{error}</div>}{!user&&<div className="meeting-login page-container"><Link to="/login">Sign in</Link> to book a private experience.</div>}
<section className="dashboard-section page-container"><div className="section-heading"><div><span className="eyebrow">AVAILABLE EXPERIENCES</span><h2>Choose an experience.</h2></div><Link className="text-link" to="/membership">Membership access →</Link></div><div className="dashboard-plans">{types.map((type,i)=><article className="dashboard-plan" key={type._id}><span className="eyebrow">{type.minimumMembershipTier||'COMMUNITY'} · {String(i+1).padStart(2,'0')}</span><h3>{type.name}</h3><strong>{money(type.price,type.currency||'USD')}</strong><small> · {type.duration} minutes</small><p>{type.description}</p><div className="meeting-meta"><span>MEMBERSHIP<strong>{type.minimumMembershipTier||'COMMUNITY'}</strong></span><span>DURATION<strong>{type.duration} min</strong></span></div>{user?<button className="button button-primary" onClick={()=>open(type)}>Book this experience</button>:<Link className="button button-ghost" to="/login">Sign in to book</Link>}</article>)}</div></section>
{token&&<section className="dashboard-section page-container"><div className="section-heading"><div><span className="eyebrow">YOUR ACTIVITY</span><h2>Upcoming &amp; past bookings.</h2></div></div>{bookings.length?<div className="booking-list">{bookings.map(b=><article className="booking-item" key={b._id}><div><strong>{b.meetingType?.name||'Meeting'}</strong><span>{new Date(b.scheduledFor).toLocaleString()}</span></div><span className="status-pill">{String(b.status).replaceAll('_',' ')}</span></article>)}</div>:<div className="dashboard-panel"><p>No bookings yet. Choose an experience above to get started.</p></div>}</section>}
{selected&&<form className="meeting-modal-backdrop" onSubmit={book}><div className="meeting-modal" role="dialog" aria-modal="true"><span className="eyebrow">BOOK EXPERIENCE</span><h2>{selected.name}</h2><p>{money(selected.price,selected.currency||'USD')} · {selected.duration} minutes</p><label>Preferred date &amp; time<input type="datetime-local" required min={minDate()} value={scheduled} onChange={e=>setScheduled(e.target.value)}/></label><label>Notes (optional)<textarea rows="4" maxLength="1000" value={notes} onChange={e=>setNotes(e.target.value)} /></label><p className="muted">After you submit, you will receive a payment token and the designated support administrator's contact details. Contact support to complete payment.</p>{error&&<p className="meeting-error">{error}</p>}<div className="meeting-modal-actions"><button className="button button-primary" disabled={submitting}>{submitting?'Creating payment request…':'Create payment request'}</button><button className="button button-ghost" type="button" onClick={()=>setSelected(null)}>Cancel</button></div></div></form>}</main>}
