import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import MembershipCard from '../components/membership/MembershipCard'
import '../styles/membership.css'
const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api'
const money = (amount, currency = 'USD') => new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(Number(amount || 0) / 100)
export default function MembershipPage() {
 const { token, user } = useAuth(); const [plans,setPlans]=useState([]),[membership,setMembership]=useState(null),[card,setCard]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[purchasing,setPurchasing]=useState(null),[otpPlan,setOtpPlan]=useState(null),[otp,setOtp]=useState(''),[otpSending,setOtpSending]=useState(false)
 useEffect(()=>{let cancelled=false;(async()=>{try{const p=await fetch(`${API_BASE_URL}/memberships/plans`),pd=await p.json();if(p.ok&&pd.success&&!cancelled)setPlans(pd.plans||[]);if(token){const m=await fetch(`${API_BASE_URL}/memberships/me`,{headers:{Authorization:`Bearer ${token}`}}),md=await m.json();if(!cancelled)setMembership(md.membership||null);if(md.success&&md.membership?.status==='ACTIVE'){const c=await fetch(`${API_BASE_URL}/memberships/card`,{headers:{Authorization:`Bearer ${token}`}}),cd=await c.json();if(c.ok&&cd.success&&!cancelled)setCard(cd.card)}}}catch{if(!cancelled)setError('Unable to load membership information.')}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[token])
 const startPurchase=async(planId,code='')=>{setError('');setPurchasing(planId);try{const r=await fetch(`${API_BASE_URL}/memberships/initialize`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({planId,...(code?{otp:code}:{})})}),d=await r.json();if(r.status===428&&d.requiresOtp){setOtpPlan(planId);setOtp('');const o=await fetch(`${API_BASE_URL}/otp/purchase/request`,{method:'POST',headers:{Authorization:`Bearer ${token}`}}),od=await o.json();if(!o.ok||!od.success)throw new Error(od.message||'Unable to send verification code.');return}if(!r.ok||!d.success)throw new Error(d.message||'Unable to start checkout.');localStorage.setItem('pendingPaymentType','MEMBERSHIP');window.location.href=d.checkout.authorizationUrl}catch(e){setError(e.message)}finally{setPurchasing(null)}}
 const activePlan=membership?.plan&&typeof membership.plan==='object'?membership.plan:plans.find(p=>p._id===membership?.plan);const active=membership?.status==='ACTIVE';const days=membership?.daysRemaining
 if(loading)return <main className="dashboard-page"><section className="dashboard-hero"><span className="eyebrow">MEMBERSHIP</span><h1>Preparing your membership dashboard.</h1><p>Loading your community access…</p></section></main>
 return <main className="dashboard-page"><header className="dashboard-hero page-container"><div><span className="eyebrow">MEMBERSHIP HUB</span><h1>{active?'Your membership.':'Find your place in the community.'}</h1><p>{active?'Manage your tier, card and renewal from one place.':'Compare the available tiers and choose the level of access that fits you.'}</p></div>{active&&<div className="dashboard-status-card"><span>STATUS</span><strong>{membership.membershipState||'ACTIVE'}</strong>{days!=null&&<small>{days} days remaining</small>}</div>}</header>
 {error&&<div className="membership-alert page-container" role="alert">{error}</div>}
 {active&&activePlan&&<section className="dashboard-section page-container"><div className="dashboard-grid"><article className="dashboard-panel"><span className="eyebrow">CURRENT TIER</span><h2>{activePlan.name}</h2><p>{activePlan.description}</p><div className="metric-row"><div><span>EXPIRES</span><strong>{membership.expiresAt?new Date(membership.expiresAt).toLocaleDateString():'—'}</strong></div><div><span>MEMBER</span><strong>{card?.memberName||user?.name||user?.username||'Member'}</strong></div></div><Link className="text-link" to="/settings">Manage account →</Link></article>{card&&<article className="dashboard-panel card-panel"><div><span className="eyebrow">DIGITAL CARD</span><h2>Carry your membership.</h2><p>Your live membership card reflects your current tier and status.</p></div><MembershipCard card={card} onPrint={()=>{document.body.classList.add('printing-membership-card');window.print();window.setTimeout(()=>document.body.classList.remove('printing-membership-card'),500)}}/></article>}</div></section>}
 <section className="dashboard-section page-container"><div className="section-heading"><div><span className="eyebrow">{active?'CHANGE OR RENEW':'MEMBERSHIP TIERS'}</span><h2>{active?'Choose your next tier.':'Choose your level of access.'}</h2></div><Link className="text-link" to="/membership/payments">Payment history →</Link></div><div className="dashboard-plans">{plans.map((plan)=><article className={`dashboard-plan ${plan.name==='Insider'?'featured':''}`} key={plan._id}><span className="eyebrow">{plan.badge||plan.name}</span><h3>{plan.name}</h3><strong>{money(plan.price,plan.currency||'USD')}</strong><small> / {(plan.durationUnit||'YEAR').toLowerCase()}</small><p>{plan.description}</p><ul>{(plan.benefits||[]).slice(0,5).map(b=><li key={b}>✓ {b}</li>)}</ul><button className="button button-primary" disabled={purchasing===plan._id||((activePlan?._id===plan._id)&&active)} onClick={()=>startPurchase(plan._id)}>{purchasing===plan._id?'Opening checkout…':activePlan?._id===plan._id?'Current membership':active?`Renew ${plan.name}`:`Join ${plan.name}`}</button></article>)}</div></section>
 <div className="dashboard-links page-container"><Link to="/meetings">Explore private meetings →</Link><Link to="/community">Enter the community →</Link></div>
 {otpPlan&&<div className="otp-overlay" role="dialog" aria-modal="true"><form className="otp-modal" onSubmit={async e=>{e.preventDefault();if(otp.length===6){const id=otpPlan;setOtpPlan(null);await startPurchase(id,otp);setOtp('')}}}><button className="otp-close" type="button" onClick={()=>setOtpPlan(null)}>×</button><span className="eyebrow">PURCHASE VERIFICATION</span><h2>Confirm your purchase</h2><p>Enter the 6-digit code sent to your account email.</p><input className="otp-input" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} placeholder="000000" required autoFocus/><button className="button button-primary" disabled={otp.length!==6}>Verify &amp; Continue</button><button className="otp-resend" type="button" disabled={otpSending} onClick={async()=>{setOtpSending(true);try{const r=await fetch(`${API_BASE_URL}/otp/purchase/request`,{method:'POST',headers:{Authorization:`Bearer ${token}`}}),d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Unable to resend code.');setError('A new code was sent.')}catch(e){setError(e.message)}finally{setOtpSending(false)}}}>{otpSending?'Sending…':'Resend code'}</button></form></div>}
 </main>
}
