const MembershipPlan = require("../models/MembershipPlan");
const Membership = require("../models/Membership");
const Payment = require("../models/Payment");
const { expireMembershipIfNecessary, getMembershipState, getMembershipDaysRemaining } = require("../services/membershipService");

const getMyMembership=async(req,res)=>{try{let membership=await Membership.findOne({user:req.user._id}).sort({createdAt:-1}).populate("plan");if(!membership)return res.status(404).json({success:false,message:"You do not have a membership."});membership=await expireMembershipIfNecessary(membership);const membershipState=getMembershipState(membership),daysRemaining=getMembershipDaysRemaining(membership);if(membership.status!=="ACTIVE")return res.status(404).json({success:false,message:membership.status==="EXPIRED"?"Your membership has expired.":"You do not have an active membership.",membership,membershipState,daysRemaining});return res.json({success:true,membership,membershipState,daysRemaining})}catch(error){console.error("Get membership error:",error);return res.status(500).json({success:false,message:"Unable to retrieve membership."})}};
const getMembershipPlans=async(req,res)=>{try{return res.json({success:true,plans:await MembershipPlan.find({isActive:true}).sort({sortOrder:1,price:1})})}catch(error){return res.status(500).json({success:false,message:"Unable to retrieve membership plans."})}};
const getPaymentHistory=async(req,res)=>{try{return res.json({success:true,payments:await Payment.find({user:req.user._id,type:{$in:["MEMBERSHIP","MEETING","GIFT"]}}).populate({path:"membership",populate:{path:"plan",select:"name slug price currency duration durationUnit"}}).sort({createdAt:-1})})}catch(error){return res.status(500).json({success:false,message:"Unable to retrieve payment history."})}};
const getMembershipCard=async(req,res)=>{try{let membership=await Membership.findOne({user:req.user._id}).sort({createdAt:-1}).populate("plan").populate("user","name username email profileImage");if(!membership)return res.status(404).json({success:false,message:"Membership not found."});membership=await expireMembershipIfNecessary(membership);if(membership.status!=="ACTIVE")return res.status(403).json({success:false,message:"An active membership is required to access the membership card.",membershipState:getMembershipState(membership),daysRemaining:getMembershipDaysRemaining(membership)});return res.json({success:true,card:{memberName:membership.user.name,username:membership.user.username,profileImage:membership.user.profileImage,membershipNumber:membership.membershipNumber,membershipType:membership.plan.name,badge:membership.plan.badge,cardDesign:membership.plan.cardDesign,benefits:membership.plan.benefits||[],startedAt:membership.startedAt,expiresAt:membership.expiresAt,status:membership.status,membershipState:getMembershipState(membership),daysRemaining:getMembershipDaysRemaining(membership)}})}catch(error){return res.status(500).json({success:false,message:"Unable to retrieve membership card."})}};
module.exports={getMembershipPlans,getMyMembership,getPaymentHistory,getMembershipCard};
